version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WEAVIATE_URL=http://weaviate:8080
      - WEAVIATE_PORT=8080
      - WEAVIATE_GRPC_PORT=50051
    depends_on:
      redis:
        condition: service_healthy
      weaviate:
        condition: service_healthy
      t2v-transformers:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 512M
    networks:
      - indexforge-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy noeviction
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    networks:
      - indexforge-network

  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.28.2
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "text2vec-transformers"
      ENABLE_MODULES: "text2vec-transformers"
      TRANSFORMERS_INFERENCE_API: "http://t2v-transformers:8080"
      TRANSFORMERS_INFERENCE_API_RETRY_AMOUNT: "20"
      TRANSFORMERS_INFERENCE_API_RETRY_TIME: "5s"
      CLUSTER_HOSTNAME: "node1"
      ENABLE_API_BASED_MODULES: "true"
      LOG_LEVEL: "info"
    volumes:
      - weaviate-data:/var/lib/weaviate
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/v1/.well-known/ready",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 45s
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
        reservations:
          cpus: "0.5"
          memory: 1G
    depends_on:
      t2v-transformers:
        condition: service_healthy
    networks:
      - indexforge-network

  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-all-MiniLM-L6-v2
    environment:
      ENABLE_CUDA: "0"
      WORKERS_PER_MODEL: "2"
      BATCHING_ENABLED: "true"
      BATCHING_WAIT_TIME: "100ms"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'python -c "import requests; requests.get(''http://localhost:8080/docs'')"',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
        reservations:
          cpus: "0.5"
          memory: 1G
    networks:
      - indexforge-network

volumes:
  weaviate-data:
    driver: local
  redis_data:
    driver: local

networks:
  indexforge-network:
    driver: bridge
