services:
  # Redis Service
  - type: redis
    name: indexforge-redis
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    plan: free
    maxmemoryPolicy: noeviction

  # Main Web Service
  - type: web
    name: indexforge
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: uvicorn src.api.main:app --host 0.0.0.0 --port $PORT --log-level info --timeout-keep-alive 75
    healthCheckPath: /health
    autoDeploy: true
    buildFilter:
      paths:
        - src/**
        - pyproject.toml
        - poetry.lock
        - render.yaml
        - build.sh
      ignoredPaths:
        - docs/**
        - tests/**
        - "*.md"
        - .git/**
        - .github/**
        - .pytest_cache/**
        - __pycache__/**
        - "*.pyc"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: POETRY_VERSION
        value: 1.7.1
      - key: PYTHONPATH
        value: .
      - key: ENVIRONMENT
        value: production
      - key: POETRY_VIRTUALENVS_CREATE
        value: "false"
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: POETRY_CACHE_DIR
        value: /opt/render/.cache/pypoetry
      # Redis connection (automatically set by Render)
      - key: REDIS_HOST
        fromService:
          type: redis
          name: indexforge-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: indexforge-redis
          property: port
      # Other secure environment variables - to be set in Render dashboard
      - key: OPENAI_API_KEY
        sync: false
      - key: WEAVIATE_URL
        sync: false
