services:
  - type: web
    name: indexforge
    runtime: python
    plan: free
    buildCommand: |
      curl -sSL https://install.python-poetry.org | python3 -
      poetry install --no-dev
    startCommand: poetry run uvicorn src.api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: WEB_CONCURRENCY
        value: 2
      - key: ENVIRONMENT
        value: production
      - key: POETRY_VIRTUALENVS_CREATE
        value: "false"
