services:
  - type: web
    name: indexforge
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: WEB_CONCURRENCY
        value: 2
      - key: ENVIRONMENT
        value: production
