groups:
  - name: istio.critical.services
    rules:
      # Critical service alerts
      - alert: CriticalServiceHighErrorRate
        expr: |
          sum(rate(istio_requests_total{destination_service=~"(ml-service|api-service).indexforge.svc.cluster.local", response_code=~"5.*"}[5m]))
          /
          sum(rate(istio_requests_total{destination_service=~"(ml-service|api-service).indexforge.svc.cluster.local"}[5m]))
          > 0.01
        for: 2m
        labels:
          severity: critical
          service_tier: critical
          team: sre
        annotations:
          summary: High error rate for {{ $labels.destination_service }}
          description: Error rate exceeded 1% for critical service {{ $labels.destination_service }}
          runbook_url: "https://runbooks.indexforge.local/critical-services/error-rate"

      # Latency alerts for critical services
      - alert: CriticalServiceLatencySpike
        expr: |
          histogram_quantile(0.95,
            sum(rate(istio_request_duration_milliseconds_bucket{
              destination_service=~"(ml-service|api-service).indexforge.svc.cluster.local"
            }[5m])) by (le, destination_service)
          ) > 200
        for: 2m
        labels:
          severity: critical
          service_tier: critical
          team: sre
        annotations:
          summary: Latency spike for {{ $labels.destination_service }}
          description: P95 latency exceeded 200ms for critical service {{ $labels.destination_service }}
          runbook_url: "https://runbooks.indexforge.local/critical-services/latency"

  - name: istio.component.health
    rules:
      # Istio control plane health
      - alert: IstiodPodDown
        expr: |
          sum(up{job="istio-mesh", app="istiod"}) < 1
        for: 1m
        labels:
          severity: critical
          component: istiod
          team: platform
        annotations:
          summary: Istiod pod is down
          description: No healthy istiod pods detected
          runbook_url: "https://runbooks.indexforge.local/istio/control-plane"

      # Gateway health
      - alert: IstioGatewayUnhealthy
        expr: |
          sum(up{job="istio-mesh", app="istio-ingressgateway"}) < 1
        for: 1m
        labels:
          severity: critical
          component: gateway
          team: platform
        annotations:
          summary: Istio Gateway is unhealthy
          description: No healthy ingress gateway pods detected
          runbook_url: "https://runbooks.indexforge.local/istio/gateway"

      # Proxy health
      - alert: SidecarProxyDisconnected
        expr: |
          sum(increase(istio_agent_pilot_xds_push_timeout_total[5m])) > 0
        for: 5m
        labels:
          severity: warning
          component: proxy
          team: platform
        annotations:
          summary: Sidecar proxy disconnection detected
          description: XDS push timeout indicates proxy connectivity issues
          runbook_url: "https://runbooks.indexforge.local/istio/proxy"

      # Resource utilization
      - alert: IstiodHighMemoryUsage
        expr: |
          container_memory_usage_bytes{container="discovery", pod=~"istiod-.*"}
          /
          container_spec_memory_limit_bytes{container="discovery", pod=~"istiod-.*"}
          > 0.85
        for: 15m
        labels:
          severity: warning
          component: istiod
          team: platform
        annotations:
          summary: High memory usage in Istiod
          description: Memory usage above 85% for Istiod
          runbook_url: "https://runbooks.indexforge.local/istio/resources"